#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-evnfm-rbac.name" . }}-create-user-realm-role-mappings-configmap
  labels: {{- include "eric-evnfm-rbac.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-evnfm-rbac.annotations" . | nindent 4 }}
data:
  user-realm-role-mappings.json: |
    [
      {
        "name": "E-VNFM Super User Role"
      },
      {
        "name": "E-VNFM UI User Role"
      }
    ]